# Generated by Django 3.2.3 on 2021-12-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0002_collectioncount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionCount',
        ),
    ]
